version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
