// Code generated by ent, DO NOT EDIT.

package oauthserver

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"go.authbricks.com/bricks/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthServer {
	return predicate.OAuthServer(sql.FieldLTE(FieldID, id))
}

// HasKeySet applies the HasEdge predicate on the "key_set" edge.
func HasKeySet() predicate.OAuthServer {
	return predicate.OAuthServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, KeySetTable, KeySetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeySetWith applies the HasEdge predicate on the "key_set" edge with a given conditions (other predicates).
func HasKeySetWith(preds ...predicate.KeySet) predicate.OAuthServer {
	return predicate.OAuthServer(func(s *sql.Selector) {
		step := newKeySetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClients applies the HasEdge predicate on the "clients" edge.
func HasClients() predicate.OAuthServer {
	return predicate.OAuthServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClientsTable, ClientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientsWith applies the HasEdge predicate on the "clients" edge with a given conditions (other predicates).
func HasClientsWith(preds ...predicate.OAuthClient) predicate.OAuthServer {
	return predicate.OAuthServer(func(s *sql.Selector) {
		step := newClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthServer) predicate.OAuthServer {
	return predicate.OAuthServer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthServer) predicate.OAuthServer {
	return predicate.OAuthServer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthServer) predicate.OAuthServer {
	return predicate.OAuthServer(sql.NotPredicates(p))
}
