// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.authbricks.com/bricks/ent/application"
	"go.authbricks.com/bricks/ent/credentials"
	"go.authbricks.com/bricks/ent/predicate"
)

// CredentialsUpdate is the builder for updating Credentials entities.
type CredentialsUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialsMutation
}

// Where appends a list predicates to the CredentialsUpdate builder.
func (cu *CredentialsUpdate) Where(ps ...predicate.Credentials) *CredentialsUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetClientID sets the "client_id" field.
func (cu *CredentialsUpdate) SetClientID(s string) *CredentialsUpdate {
	cu.mutation.SetClientID(s)
	return cu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (cu *CredentialsUpdate) SetNillableClientID(s *string) *CredentialsUpdate {
	if s != nil {
		cu.SetClientID(*s)
	}
	return cu
}

// SetClientSecret sets the "client_secret" field.
func (cu *CredentialsUpdate) SetClientSecret(s string) *CredentialsUpdate {
	cu.mutation.SetClientSecret(s)
	return cu
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (cu *CredentialsUpdate) SetNillableClientSecret(s *string) *CredentialsUpdate {
	if s != nil {
		cu.SetClientSecret(*s)
	}
	return cu
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (cu *CredentialsUpdate) SetApplicationID(id string) *CredentialsUpdate {
	cu.mutation.SetApplicationID(id)
	return cu
}

// SetNillableApplicationID sets the "application" edge to the Application entity by ID if the given value is not nil.
func (cu *CredentialsUpdate) SetNillableApplicationID(id *string) *CredentialsUpdate {
	if id != nil {
		cu = cu.SetApplicationID(*id)
	}
	return cu
}

// SetApplication sets the "application" edge to the Application entity.
func (cu *CredentialsUpdate) SetApplication(a *Application) *CredentialsUpdate {
	return cu.SetApplicationID(a.ID)
}

// Mutation returns the CredentialsMutation object of the builder.
func (cu *CredentialsUpdate) Mutation() *CredentialsMutation {
	return cu.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (cu *CredentialsUpdate) ClearApplication() *CredentialsUpdate {
	cu.mutation.ClearApplication()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CredentialsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CredentialsUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CredentialsUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CredentialsUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CredentialsUpdate) check() error {
	if v, ok := cu.mutation.ClientID(); ok {
		if err := credentials.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Credentials.client_id": %w`, err)}
		}
	}
	return nil
}

func (cu *CredentialsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentials.Table, credentials.Columns, sqlgraph.NewFieldSpec(credentials.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.ClientID(); ok {
		_spec.SetField(credentials.FieldClientID, field.TypeString, value)
	}
	if value, ok := cu.mutation.ClientSecret(); ok {
		_spec.SetField(credentials.FieldClientSecret, field.TypeString, value)
	}
	if cu.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentials.ApplicationTable,
			Columns: []string{credentials.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentials.ApplicationTable,
			Columns: []string{credentials.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentials.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CredentialsUpdateOne is the builder for updating a single Credentials entity.
type CredentialsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialsMutation
}

// SetClientID sets the "client_id" field.
func (cuo *CredentialsUpdateOne) SetClientID(s string) *CredentialsUpdateOne {
	cuo.mutation.SetClientID(s)
	return cuo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (cuo *CredentialsUpdateOne) SetNillableClientID(s *string) *CredentialsUpdateOne {
	if s != nil {
		cuo.SetClientID(*s)
	}
	return cuo
}

// SetClientSecret sets the "client_secret" field.
func (cuo *CredentialsUpdateOne) SetClientSecret(s string) *CredentialsUpdateOne {
	cuo.mutation.SetClientSecret(s)
	return cuo
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (cuo *CredentialsUpdateOne) SetNillableClientSecret(s *string) *CredentialsUpdateOne {
	if s != nil {
		cuo.SetClientSecret(*s)
	}
	return cuo
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (cuo *CredentialsUpdateOne) SetApplicationID(id string) *CredentialsUpdateOne {
	cuo.mutation.SetApplicationID(id)
	return cuo
}

// SetNillableApplicationID sets the "application" edge to the Application entity by ID if the given value is not nil.
func (cuo *CredentialsUpdateOne) SetNillableApplicationID(id *string) *CredentialsUpdateOne {
	if id != nil {
		cuo = cuo.SetApplicationID(*id)
	}
	return cuo
}

// SetApplication sets the "application" edge to the Application entity.
func (cuo *CredentialsUpdateOne) SetApplication(a *Application) *CredentialsUpdateOne {
	return cuo.SetApplicationID(a.ID)
}

// Mutation returns the CredentialsMutation object of the builder.
func (cuo *CredentialsUpdateOne) Mutation() *CredentialsMutation {
	return cuo.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (cuo *CredentialsUpdateOne) ClearApplication() *CredentialsUpdateOne {
	cuo.mutation.ClearApplication()
	return cuo
}

// Where appends a list predicates to the CredentialsUpdate builder.
func (cuo *CredentialsUpdateOne) Where(ps ...predicate.Credentials) *CredentialsUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CredentialsUpdateOne) Select(field string, fields ...string) *CredentialsUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Credentials entity.
func (cuo *CredentialsUpdateOne) Save(ctx context.Context) (*Credentials, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CredentialsUpdateOne) SaveX(ctx context.Context) *Credentials {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CredentialsUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CredentialsUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CredentialsUpdateOne) check() error {
	if v, ok := cuo.mutation.ClientID(); ok {
		if err := credentials.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Credentials.client_id": %w`, err)}
		}
	}
	return nil
}

func (cuo *CredentialsUpdateOne) sqlSave(ctx context.Context) (_node *Credentials, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentials.Table, credentials.Columns, sqlgraph.NewFieldSpec(credentials.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Credentials.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentials.FieldID)
		for _, f := range fields {
			if !credentials.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentials.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.ClientID(); ok {
		_spec.SetField(credentials.FieldClientID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ClientSecret(); ok {
		_spec.SetField(credentials.FieldClientSecret, field.TypeString, value)
	}
	if cuo.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentials.ApplicationTable,
			Columns: []string{credentials.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentials.ApplicationTable,
			Columns: []string{credentials.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Credentials{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentials.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
