// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.authbricks.com/bricks/ent/jwksendpointconfig"
	"go.authbricks.com/bricks/ent/service"
)

// JwksEndpointConfig is the model entity for the JwksEndpointConfig schema.
type JwksEndpointConfig struct {
	config `hcl:"-" json:"-"`
	// ID of the ent.
	ID string `json:"id" hcl:"id"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint" hcl:"endpoint"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JwksEndpointConfigQuery when eager-loading is set.
	Edges                                JwksEndpointConfigEdges `json:"edges"`
	service_service_jwks_endpoint_config *string
	selectValues                         sql.SelectValues
}

// JwksEndpointConfigEdges holds the relations/edges for other nodes in the graph.
type JwksEndpointConfigEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JwksEndpointConfigEdges) ServiceOrErr() (*Service, error) {
	if e.Service != nil {
		return e.Service, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: service.Label}
	}
	return nil, &NotLoadedError{edge: "service"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JwksEndpointConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jwksendpointconfig.FieldID, jwksendpointconfig.FieldEndpoint:
			values[i] = new(sql.NullString)
		case jwksendpointconfig.ForeignKeys[0]: // service_service_jwks_endpoint_config
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JwksEndpointConfig fields.
func (jec *JwksEndpointConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jwksendpointconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				jec.ID = value.String
			}
		case jwksendpointconfig.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				jec.Endpoint = value.String
			}
		case jwksendpointconfig.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_service_jwks_endpoint_config", values[i])
			} else if value.Valid {
				jec.service_service_jwks_endpoint_config = new(string)
				*jec.service_service_jwks_endpoint_config = value.String
			}
		default:
			jec.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JwksEndpointConfig.
// This includes values selected through modifiers, order, etc.
func (jec *JwksEndpointConfig) Value(name string) (ent.Value, error) {
	return jec.selectValues.Get(name)
}

// QueryService queries the "service" edge of the JwksEndpointConfig entity.
func (jec *JwksEndpointConfig) QueryService() *ServiceQuery {
	return NewJwksEndpointConfigClient(jec.config).QueryService(jec)
}

// Update returns a builder for updating this JwksEndpointConfig.
// Note that you need to call JwksEndpointConfig.Unwrap() before calling this method if this JwksEndpointConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (jec *JwksEndpointConfig) Update() *JwksEndpointConfigUpdateOne {
	return NewJwksEndpointConfigClient(jec.config).UpdateOne(jec)
}

// Unwrap unwraps the JwksEndpointConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (jec *JwksEndpointConfig) Unwrap() *JwksEndpointConfig {
	_tx, ok := jec.config.driver.(*txDriver)
	if !ok {
		panic("ent: JwksEndpointConfig is not a transactional entity")
	}
	jec.config.driver = _tx.drv
	return jec
}

// String implements the fmt.Stringer.
func (jec *JwksEndpointConfig) String() string {
	var builder strings.Builder
	builder.WriteString("JwksEndpointConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", jec.ID))
	builder.WriteString("endpoint=")
	builder.WriteString(jec.Endpoint)
	builder.WriteByte(')')
	return builder.String()
}

// JwksEndpointConfigs is a parsable slice of JwksEndpointConfig.
type JwksEndpointConfigs []*JwksEndpointConfig
