// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.authbricks.com/bricks/ent/loginendpointconfig"
	"go.authbricks.com/bricks/ent/service"
)

// LoginEndpointConfig is the model entity for the LoginEndpointConfig schema.
type LoginEndpointConfig struct {
	config `hcl:"-" json:"-"`
	// ID of the ent.
	ID string `json:"id" hcl:"id"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint" hcl:"endpoint"`
	// SessionTimeout holds the value of the "session_timeout" field.
	SessionTimeout int64 `json:"session_timeout" hcl:"session_timeout"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginEndpointConfigQuery when eager-loading is set.
	Edges                                 LoginEndpointConfigEdges `json:"edges"`
	service_service_login_endpoint_config *string
	selectValues                          sql.SelectValues
}

// LoginEndpointConfigEdges holds the relations/edges for other nodes in the graph.
type LoginEndpointConfigEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginEndpointConfigEdges) ServiceOrErr() (*Service, error) {
	if e.Service != nil {
		return e.Service, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: service.Label}
	}
	return nil, &NotLoadedError{edge: "service"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginEndpointConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginendpointconfig.FieldSessionTimeout:
			values[i] = new(sql.NullInt64)
		case loginendpointconfig.FieldID, loginendpointconfig.FieldEndpoint:
			values[i] = new(sql.NullString)
		case loginendpointconfig.ForeignKeys[0]: // service_service_login_endpoint_config
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginEndpointConfig fields.
func (lec *LoginEndpointConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginendpointconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				lec.ID = value.String
			}
		case loginendpointconfig.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				lec.Endpoint = value.String
			}
		case loginendpointconfig.FieldSessionTimeout:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_timeout", values[i])
			} else if value.Valid {
				lec.SessionTimeout = value.Int64
			}
		case loginendpointconfig.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_service_login_endpoint_config", values[i])
			} else if value.Valid {
				lec.service_service_login_endpoint_config = new(string)
				*lec.service_service_login_endpoint_config = value.String
			}
		default:
			lec.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginEndpointConfig.
// This includes values selected through modifiers, order, etc.
func (lec *LoginEndpointConfig) Value(name string) (ent.Value, error) {
	return lec.selectValues.Get(name)
}

// QueryService queries the "service" edge of the LoginEndpointConfig entity.
func (lec *LoginEndpointConfig) QueryService() *ServiceQuery {
	return NewLoginEndpointConfigClient(lec.config).QueryService(lec)
}

// Update returns a builder for updating this LoginEndpointConfig.
// Note that you need to call LoginEndpointConfig.Unwrap() before calling this method if this LoginEndpointConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (lec *LoginEndpointConfig) Update() *LoginEndpointConfigUpdateOne {
	return NewLoginEndpointConfigClient(lec.config).UpdateOne(lec)
}

// Unwrap unwraps the LoginEndpointConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lec *LoginEndpointConfig) Unwrap() *LoginEndpointConfig {
	_tx, ok := lec.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginEndpointConfig is not a transactional entity")
	}
	lec.config.driver = _tx.drv
	return lec
}

// String implements the fmt.Stringer.
func (lec *LoginEndpointConfig) String() string {
	var builder strings.Builder
	builder.WriteString("LoginEndpointConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lec.ID))
	builder.WriteString("endpoint=")
	builder.WriteString(lec.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("session_timeout=")
	builder.WriteString(fmt.Sprintf("%v", lec.SessionTimeout))
	builder.WriteByte(')')
	return builder.String()
}

// LoginEndpointConfigs is a parsable slice of LoginEndpointConfig.
type LoginEndpointConfigs []*LoginEndpointConfig
