// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.authbricks.com/bricks/ent/predicate"
	"go.authbricks.com/bricks/ent/service"
	"go.authbricks.com/bricks/ent/serviceintrospectionendpointconfig"
)

// ServiceIntrospectionEndpointConfigQuery is the builder for querying ServiceIntrospectionEndpointConfig entities.
type ServiceIntrospectionEndpointConfigQuery struct {
	config
	ctx         *QueryContext
	order       []serviceintrospectionendpointconfig.OrderOption
	inters      []Interceptor
	predicates  []predicate.ServiceIntrospectionEndpointConfig
	withService *ServiceQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceIntrospectionEndpointConfigQuery builder.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Where(ps ...predicate.ServiceIntrospectionEndpointConfig) *ServiceIntrospectionEndpointConfigQuery {
	siecq.predicates = append(siecq.predicates, ps...)
	return siecq
}

// Limit the number of records to be returned by this query.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Limit(limit int) *ServiceIntrospectionEndpointConfigQuery {
	siecq.ctx.Limit = &limit
	return siecq
}

// Offset to start from.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Offset(offset int) *ServiceIntrospectionEndpointConfigQuery {
	siecq.ctx.Offset = &offset
	return siecq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Unique(unique bool) *ServiceIntrospectionEndpointConfigQuery {
	siecq.ctx.Unique = &unique
	return siecq
}

// Order specifies how the records should be ordered.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Order(o ...serviceintrospectionendpointconfig.OrderOption) *ServiceIntrospectionEndpointConfigQuery {
	siecq.order = append(siecq.order, o...)
	return siecq
}

// QueryService chains the current query on the "service" edge.
func (siecq *ServiceIntrospectionEndpointConfigQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: siecq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := siecq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := siecq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceintrospectionendpointconfig.Table, serviceintrospectionendpointconfig.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, serviceintrospectionendpointconfig.ServiceTable, serviceintrospectionendpointconfig.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(siecq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceIntrospectionEndpointConfig entity from the query.
// Returns a *NotFoundError when no ServiceIntrospectionEndpointConfig was found.
func (siecq *ServiceIntrospectionEndpointConfigQuery) First(ctx context.Context) (*ServiceIntrospectionEndpointConfig, error) {
	nodes, err := siecq.Limit(1).All(setContextOp(ctx, siecq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serviceintrospectionendpointconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) FirstX(ctx context.Context) *ServiceIntrospectionEndpointConfig {
	node, err := siecq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceIntrospectionEndpointConfig ID from the query.
// Returns a *NotFoundError when no ServiceIntrospectionEndpointConfig ID was found.
func (siecq *ServiceIntrospectionEndpointConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = siecq.Limit(1).IDs(setContextOp(ctx, siecq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serviceintrospectionendpointconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := siecq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceIntrospectionEndpointConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceIntrospectionEndpointConfig entity is found.
// Returns a *NotFoundError when no ServiceIntrospectionEndpointConfig entities are found.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Only(ctx context.Context) (*ServiceIntrospectionEndpointConfig, error) {
	nodes, err := siecq.Limit(2).All(setContextOp(ctx, siecq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serviceintrospectionendpointconfig.Label}
	default:
		return nil, &NotSingularError{serviceintrospectionendpointconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) OnlyX(ctx context.Context) *ServiceIntrospectionEndpointConfig {
	node, err := siecq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceIntrospectionEndpointConfig ID in the query.
// Returns a *NotSingularError when more than one ServiceIntrospectionEndpointConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (siecq *ServiceIntrospectionEndpointConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = siecq.Limit(2).IDs(setContextOp(ctx, siecq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serviceintrospectionendpointconfig.Label}
	default:
		err = &NotSingularError{serviceintrospectionendpointconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := siecq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceIntrospectionEndpointConfigs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) All(ctx context.Context) ([]*ServiceIntrospectionEndpointConfig, error) {
	ctx = setContextOp(ctx, siecq.ctx, "All")
	if err := siecq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServiceIntrospectionEndpointConfig, *ServiceIntrospectionEndpointConfigQuery]()
	return withInterceptors[[]*ServiceIntrospectionEndpointConfig](ctx, siecq, qr, siecq.inters)
}

// AllX is like All, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) AllX(ctx context.Context) []*ServiceIntrospectionEndpointConfig {
	nodes, err := siecq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceIntrospectionEndpointConfig IDs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if siecq.ctx.Unique == nil && siecq.path != nil {
		siecq.Unique(true)
	}
	ctx = setContextOp(ctx, siecq.ctx, "IDs")
	if err = siecq.Select(serviceintrospectionendpointconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := siecq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, siecq.ctx, "Count")
	if err := siecq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, siecq, querierCount[*ServiceIntrospectionEndpointConfigQuery](), siecq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) CountX(ctx context.Context) int {
	count, err := siecq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, siecq.ctx, "Exist")
	switch _, err := siecq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (siecq *ServiceIntrospectionEndpointConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := siecq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceIntrospectionEndpointConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Clone() *ServiceIntrospectionEndpointConfigQuery {
	if siecq == nil {
		return nil
	}
	return &ServiceIntrospectionEndpointConfigQuery{
		config:      siecq.config,
		ctx:         siecq.ctx.Clone(),
		order:       append([]serviceintrospectionendpointconfig.OrderOption{}, siecq.order...),
		inters:      append([]Interceptor{}, siecq.inters...),
		predicates:  append([]predicate.ServiceIntrospectionEndpointConfig{}, siecq.predicates...),
		withService: siecq.withService.Clone(),
		// clone intermediate query.
		sql:  siecq.sql.Clone(),
		path: siecq.path,
	}
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (siecq *ServiceIntrospectionEndpointConfigQuery) WithService(opts ...func(*ServiceQuery)) *ServiceIntrospectionEndpointConfigQuery {
	query := (&ServiceClient{config: siecq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	siecq.withService = query
	return siecq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Endpoint string `json:"endpoint" hcl:"endpoint"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceIntrospectionEndpointConfig.Query().
//		GroupBy(serviceintrospectionendpointconfig.FieldEndpoint).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (siecq *ServiceIntrospectionEndpointConfigQuery) GroupBy(field string, fields ...string) *ServiceIntrospectionEndpointConfigGroupBy {
	siecq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServiceIntrospectionEndpointConfigGroupBy{build: siecq}
	grbuild.flds = &siecq.ctx.Fields
	grbuild.label = serviceintrospectionendpointconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Endpoint string `json:"endpoint" hcl:"endpoint"`
//	}
//
//	client.ServiceIntrospectionEndpointConfig.Query().
//		Select(serviceintrospectionendpointconfig.FieldEndpoint).
//		Scan(ctx, &v)
func (siecq *ServiceIntrospectionEndpointConfigQuery) Select(fields ...string) *ServiceIntrospectionEndpointConfigSelect {
	siecq.ctx.Fields = append(siecq.ctx.Fields, fields...)
	sbuild := &ServiceIntrospectionEndpointConfigSelect{ServiceIntrospectionEndpointConfigQuery: siecq}
	sbuild.label = serviceintrospectionendpointconfig.Label
	sbuild.flds, sbuild.scan = &siecq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServiceIntrospectionEndpointConfigSelect configured with the given aggregations.
func (siecq *ServiceIntrospectionEndpointConfigQuery) Aggregate(fns ...AggregateFunc) *ServiceIntrospectionEndpointConfigSelect {
	return siecq.Select().Aggregate(fns...)
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range siecq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, siecq); err != nil {
				return err
			}
		}
	}
	for _, f := range siecq.ctx.Fields {
		if !serviceintrospectionendpointconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if siecq.path != nil {
		prev, err := siecq.path(ctx)
		if err != nil {
			return err
		}
		siecq.sql = prev
	}
	return nil
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceIntrospectionEndpointConfig, error) {
	var (
		nodes       = []*ServiceIntrospectionEndpointConfig{}
		withFKs     = siecq.withFKs
		_spec       = siecq.querySpec()
		loadedTypes = [1]bool{
			siecq.withService != nil,
		}
	)
	if siecq.withService != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, serviceintrospectionendpointconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceIntrospectionEndpointConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceIntrospectionEndpointConfig{config: siecq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, siecq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := siecq.withService; query != nil {
		if err := siecq.loadService(ctx, query, nodes, nil,
			func(n *ServiceIntrospectionEndpointConfig, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*ServiceIntrospectionEndpointConfig, init func(*ServiceIntrospectionEndpointConfig), assign func(*ServiceIntrospectionEndpointConfig, *Service)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ServiceIntrospectionEndpointConfig)
	for i := range nodes {
		if nodes[i].service_service_introspection_endpoint_config == nil {
			continue
		}
		fk := *nodes[i].service_service_introspection_endpoint_config
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_service_introspection_endpoint_config" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := siecq.querySpec()
	_spec.Node.Columns = siecq.ctx.Fields
	if len(siecq.ctx.Fields) > 0 {
		_spec.Unique = siecq.ctx.Unique != nil && *siecq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, siecq.driver, _spec)
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serviceintrospectionendpointconfig.Table, serviceintrospectionendpointconfig.Columns, sqlgraph.NewFieldSpec(serviceintrospectionendpointconfig.FieldID, field.TypeString))
	_spec.From = siecq.sql
	if unique := siecq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if siecq.path != nil {
		_spec.Unique = true
	}
	if fields := siecq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceintrospectionendpointconfig.FieldID)
		for i := range fields {
			if fields[i] != serviceintrospectionendpointconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := siecq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := siecq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := siecq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := siecq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (siecq *ServiceIntrospectionEndpointConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(siecq.driver.Dialect())
	t1 := builder.Table(serviceintrospectionendpointconfig.Table)
	columns := siecq.ctx.Fields
	if len(columns) == 0 {
		columns = serviceintrospectionendpointconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if siecq.sql != nil {
		selector = siecq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if siecq.ctx.Unique != nil && *siecq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range siecq.predicates {
		p(selector)
	}
	for _, p := range siecq.order {
		p(selector)
	}
	if offset := siecq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := siecq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceIntrospectionEndpointConfigGroupBy is the group-by builder for ServiceIntrospectionEndpointConfig entities.
type ServiceIntrospectionEndpointConfigGroupBy struct {
	selector
	build *ServiceIntrospectionEndpointConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (siecgb *ServiceIntrospectionEndpointConfigGroupBy) Aggregate(fns ...AggregateFunc) *ServiceIntrospectionEndpointConfigGroupBy {
	siecgb.fns = append(siecgb.fns, fns...)
	return siecgb
}

// Scan applies the selector query and scans the result into the given value.
func (siecgb *ServiceIntrospectionEndpointConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, siecgb.build.ctx, "GroupBy")
	if err := siecgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceIntrospectionEndpointConfigQuery, *ServiceIntrospectionEndpointConfigGroupBy](ctx, siecgb.build, siecgb, siecgb.build.inters, v)
}

func (siecgb *ServiceIntrospectionEndpointConfigGroupBy) sqlScan(ctx context.Context, root *ServiceIntrospectionEndpointConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(siecgb.fns))
	for _, fn := range siecgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*siecgb.flds)+len(siecgb.fns))
		for _, f := range *siecgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*siecgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := siecgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServiceIntrospectionEndpointConfigSelect is the builder for selecting fields of ServiceIntrospectionEndpointConfig entities.
type ServiceIntrospectionEndpointConfigSelect struct {
	*ServiceIntrospectionEndpointConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (siecs *ServiceIntrospectionEndpointConfigSelect) Aggregate(fns ...AggregateFunc) *ServiceIntrospectionEndpointConfigSelect {
	siecs.fns = append(siecs.fns, fns...)
	return siecs
}

// Scan applies the selector query and scans the result into the given value.
func (siecs *ServiceIntrospectionEndpointConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, siecs.ctx, "Select")
	if err := siecs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceIntrospectionEndpointConfigQuery, *ServiceIntrospectionEndpointConfigSelect](ctx, siecs.ServiceIntrospectionEndpointConfigQuery, siecs, siecs.inters, v)
}

func (siecs *ServiceIntrospectionEndpointConfigSelect) sqlScan(ctx context.Context, root *ServiceIntrospectionEndpointConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(siecs.fns))
	for _, fn := range siecs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*siecs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := siecs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
