// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.authbricks.com/bricks/ent/service"
	"go.authbricks.com/bricks/ent/serviceauthorizationendpointconfig"
)

// ServiceAuthorizationEndpointConfigCreate is the builder for creating a ServiceAuthorizationEndpointConfig entity.
type ServiceAuthorizationEndpointConfigCreate struct {
	config
	mutation *ServiceAuthorizationEndpointConfigMutation
	hooks    []Hook
}

// SetEndpoint sets the "endpoint" field.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetEndpoint(s string) *ServiceAuthorizationEndpointConfigCreate {
	saecc.mutation.SetEndpoint(s)
	return saecc
}

// SetPkceRequired sets the "pkce_required" field.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetPkceRequired(b bool) *ServiceAuthorizationEndpointConfigCreate {
	saecc.mutation.SetPkceRequired(b)
	return saecc
}

// SetPkceS256CodeChallengeMethodRequired sets the "pkce_s256_code_challenge_method_required" field.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetPkceS256CodeChallengeMethodRequired(b bool) *ServiceAuthorizationEndpointConfigCreate {
	saecc.mutation.SetPkceS256CodeChallengeMethodRequired(b)
	return saecc
}

// SetID sets the "id" field.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetID(s string) *ServiceAuthorizationEndpointConfigCreate {
	saecc.mutation.SetID(s)
	return saecc
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetServiceID(id string) *ServiceAuthorizationEndpointConfigCreate {
	saecc.mutation.SetServiceID(id)
	return saecc
}

// SetService sets the "service" edge to the Service entity.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SetService(s *Service) *ServiceAuthorizationEndpointConfigCreate {
	return saecc.SetServiceID(s.ID)
}

// Mutation returns the ServiceAuthorizationEndpointConfigMutation object of the builder.
func (saecc *ServiceAuthorizationEndpointConfigCreate) Mutation() *ServiceAuthorizationEndpointConfigMutation {
	return saecc.mutation
}

// Save creates the ServiceAuthorizationEndpointConfig in the database.
func (saecc *ServiceAuthorizationEndpointConfigCreate) Save(ctx context.Context) (*ServiceAuthorizationEndpointConfig, error) {
	return withHooks(ctx, saecc.sqlSave, saecc.mutation, saecc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (saecc *ServiceAuthorizationEndpointConfigCreate) SaveX(ctx context.Context) *ServiceAuthorizationEndpointConfig {
	v, err := saecc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (saecc *ServiceAuthorizationEndpointConfigCreate) Exec(ctx context.Context) error {
	_, err := saecc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (saecc *ServiceAuthorizationEndpointConfigCreate) ExecX(ctx context.Context) {
	if err := saecc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (saecc *ServiceAuthorizationEndpointConfigCreate) check() error {
	if _, ok := saecc.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "ServiceAuthorizationEndpointConfig.endpoint"`)}
	}
	if v, ok := saecc.mutation.Endpoint(); ok {
		if err := serviceauthorizationendpointconfig.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ServiceAuthorizationEndpointConfig.endpoint": %w`, err)}
		}
	}
	if _, ok := saecc.mutation.PkceRequired(); !ok {
		return &ValidationError{Name: "pkce_required", err: errors.New(`ent: missing required field "ServiceAuthorizationEndpointConfig.pkce_required"`)}
	}
	if _, ok := saecc.mutation.PkceS256CodeChallengeMethodRequired(); !ok {
		return &ValidationError{Name: "pkce_s256_code_challenge_method_required", err: errors.New(`ent: missing required field "ServiceAuthorizationEndpointConfig.pkce_s256_code_challenge_method_required"`)}
	}
	if v, ok := saecc.mutation.ID(); ok {
		if err := serviceauthorizationendpointconfig.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ServiceAuthorizationEndpointConfig.id": %w`, err)}
		}
	}
	if _, ok := saecc.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "ServiceAuthorizationEndpointConfig.service"`)}
	}
	return nil
}

func (saecc *ServiceAuthorizationEndpointConfigCreate) sqlSave(ctx context.Context) (*ServiceAuthorizationEndpointConfig, error) {
	if err := saecc.check(); err != nil {
		return nil, err
	}
	_node, _spec := saecc.createSpec()
	if err := sqlgraph.CreateNode(ctx, saecc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ServiceAuthorizationEndpointConfig.ID type: %T", _spec.ID.Value)
		}
	}
	saecc.mutation.id = &_node.ID
	saecc.mutation.done = true
	return _node, nil
}

func (saecc *ServiceAuthorizationEndpointConfigCreate) createSpec() (*ServiceAuthorizationEndpointConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceAuthorizationEndpointConfig{config: saecc.config}
		_spec = sqlgraph.NewCreateSpec(serviceauthorizationendpointconfig.Table, sqlgraph.NewFieldSpec(serviceauthorizationendpointconfig.FieldID, field.TypeString))
	)
	if id, ok := saecc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := saecc.mutation.Endpoint(); ok {
		_spec.SetField(serviceauthorizationendpointconfig.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := saecc.mutation.PkceRequired(); ok {
		_spec.SetField(serviceauthorizationendpointconfig.FieldPkceRequired, field.TypeBool, value)
		_node.PkceRequired = value
	}
	if value, ok := saecc.mutation.PkceS256CodeChallengeMethodRequired(); ok {
		_spec.SetField(serviceauthorizationendpointconfig.FieldPkceS256CodeChallengeMethodRequired, field.TypeBool, value)
		_node.PkceS256CodeChallengeMethodRequired = value
	}
	if nodes := saecc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   serviceauthorizationendpointconfig.ServiceTable,
			Columns: []string{serviceauthorizationendpointconfig.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.service_service_authorization_endpoint_config = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceAuthorizationEndpointConfigCreateBulk is the builder for creating many ServiceAuthorizationEndpointConfig entities in bulk.
type ServiceAuthorizationEndpointConfigCreateBulk struct {
	config
	err      error
	builders []*ServiceAuthorizationEndpointConfigCreate
}

// Save creates the ServiceAuthorizationEndpointConfig entities in the database.
func (saeccb *ServiceAuthorizationEndpointConfigCreateBulk) Save(ctx context.Context) ([]*ServiceAuthorizationEndpointConfig, error) {
	if saeccb.err != nil {
		return nil, saeccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(saeccb.builders))
	nodes := make([]*ServiceAuthorizationEndpointConfig, len(saeccb.builders))
	mutators := make([]Mutator, len(saeccb.builders))
	for i := range saeccb.builders {
		func(i int, root context.Context) {
			builder := saeccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceAuthorizationEndpointConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, saeccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, saeccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, saeccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (saeccb *ServiceAuthorizationEndpointConfigCreateBulk) SaveX(ctx context.Context) []*ServiceAuthorizationEndpointConfig {
	v, err := saeccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (saeccb *ServiceAuthorizationEndpointConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := saeccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (saeccb *ServiceAuthorizationEndpointConfigCreateBulk) ExecX(ctx context.Context) {
	if err := saeccb.Exec(ctx); err != nil {
		panic(err)
	}
}
