baseURL = 'https://authforge.id'
languageCode = 'en-us'
title = 'authforge.id'

# Code higlighting settings
pygmentsCodefences            = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions               = ""
pygmentsStyle                 = "monokai"
pygmentsUseClasses            = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
      unsafe = true


[[module.imports]]
path = "github.com/bep/docuapi/v2"
