// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldHashedPassword holds the string denoting the hashed_password field in the database.
	FieldHashedPassword = "hashed_password"
	// EdgeStandardClaims holds the string denoting the standard_claims edge name in mutations.
	EdgeStandardClaims = "standard_claims"
	// EdgeEmailPasswordConnection holds the string denoting the email_password_connection edge name in mutations.
	EdgeEmailPasswordConnection = "email_password_connection"
	// EdgeOidcConnections holds the string denoting the oidc_connections edge name in mutations.
	EdgeOidcConnections = "oidc_connections"
	// Table holds the table name of the user in the database.
	Table = "users"
	// StandardClaimsTable is the table that holds the standard_claims relation/edge.
	StandardClaimsTable = "standard_claims"
	// StandardClaimsInverseTable is the table name for the StandardClaims entity.
	// It exists in this package in order to avoid circular dependency with the "standardclaims" package.
	StandardClaimsInverseTable = "standard_claims"
	// StandardClaimsColumn is the table column denoting the standard_claims relation/edge.
	StandardClaimsColumn = "user_standard_claims"
	// EmailPasswordConnectionTable is the table that holds the email_password_connection relation/edge.
	EmailPasswordConnectionTable = "users"
	// EmailPasswordConnectionInverseTable is the table name for the EmailPasswordConnection entity.
	// It exists in this package in order to avoid circular dependency with the "emailpasswordconnection" package.
	EmailPasswordConnectionInverseTable = "email_password_connections"
	// EmailPasswordConnectionColumn is the table column denoting the email_password_connection relation/edge.
	EmailPasswordConnectionColumn = "email_password_connection_users"
	// OidcConnectionsTable is the table that holds the oidc_connections relation/edge.
	OidcConnectionsTable = "users"
	// OidcConnectionsInverseTable is the table name for the OIDCConnection entity.
	// It exists in this package in order to avoid circular dependency with the "oidcconnection" package.
	OidcConnectionsInverseTable = "oidc_connections"
	// OidcConnectionsColumn is the table column denoting the oidc_connections relation/edge.
	OidcConnectionsColumn = "oidc_connection_users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldHashedPassword,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"email_password_connection_users",
	"oidc_connection_users",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByHashedPassword orders the results by the hashed_password field.
func ByHashedPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashedPassword, opts...).ToFunc()
}

// ByStandardClaimsField orders the results by standard_claims field.
func ByStandardClaimsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStandardClaimsStep(), sql.OrderByField(field, opts...))
	}
}

// ByEmailPasswordConnectionField orders the results by email_password_connection field.
func ByEmailPasswordConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailPasswordConnectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByOidcConnectionsField orders the results by oidc_connections field.
func ByOidcConnectionsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOidcConnectionsStep(), sql.OrderByField(field, opts...))
	}
}
func newStandardClaimsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StandardClaimsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, StandardClaimsTable, StandardClaimsColumn),
	)
}
func newEmailPasswordConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailPasswordConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, EmailPasswordConnectionTable, EmailPasswordConnectionColumn),
	)
}
func newOidcConnectionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OidcConnectionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OidcConnectionsTable, OidcConnectionsColumn),
	)
}
