name: run tests in CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      submodules: recursive
      fetch-depth: 0
  - name: Setup Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.23.4
  - name: Run tests
    run: go test -v ./...
