// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// AuthorizationCode is the predicate function for authorizationcode builders.
type AuthorizationCode func(*sql.Selector)

// AuthorizationPayload is the predicate function for authorizationpayload builders.
type AuthorizationPayload func(*sql.Selector)

// CookieStore is the predicate function for cookiestore builders.
type CookieStore func(*sql.Selector)

// Credentials is the predicate function for credentials builders.
type Credentials func(*sql.Selector)

// KeySet is the predicate function for keyset builders.
type KeySet func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// ServiceAuthorizationEndpointConfig is the predicate function for serviceauthorizationendpointconfig builders.
type ServiceAuthorizationEndpointConfig func(*sql.Selector)

// ServiceIntrospectionEndpointConfig is the predicate function for serviceintrospectionendpointconfig builders.
type ServiceIntrospectionEndpointConfig func(*sql.Selector)

// ServiceJWKSEndpointConfig is the predicate function for servicejwksendpointconfig builders.
type ServiceJWKSEndpointConfig func(*sql.Selector)

// ServiceTokenEndpointConfig is the predicate function for servicetokenendpointconfig builders.
type ServiceTokenEndpointConfig func(*sql.Selector)

// ServiceUserInfoEndpointConfig is the predicate function for serviceuserinfoendpointconfig builders.
type ServiceUserInfoEndpointConfig func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SigningKey is the predicate function for signingkey builders.
type SigningKey func(*sql.Selector)

// StandardClaims is the predicate function for standardclaims builders.
type StandardClaims func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPool is the predicate function for userpool builders.
type UserPool func(*sql.Selector)

// WellKnownEndpointConfig is the predicate function for wellknownendpointconfig builders.
type WellKnownEndpointConfig func(*sql.Selector)
